<?php

$tableSettings = [
    'headers' => [
        [
            'title' => 'Presidio',
            'align' => 'start',
            'key' => 'nome'
        ],
        [
            'title' => 'Rosso in attesa',
            'align' => 'end',
            'key' => 'data.data.rosso.value'
        ],
        [
            'title' => 'Arancione in attesa',
            'align' => 'end',
            'key' => 'data.data.arancione.value'
        ],
        [
            'title' => 'Azzurro in attesa',
            'align' => 'end',
            'key' => 'data.data.azzurro.value'
        ],
        [
            'title' => 'Verde in attesa',
            'align' => 'end',
            'key' => 'data.data.verde.value'
        ],
        [
            'title' => 'Bianco in attesa',
            'align' => 'end',
            'key' => 'data.data.bianco.value'
        ],
        [
            'title' => 'Totali',
            'align' => 'end',
            'key' => 'data.data.totali.value'
        ],
    ],
    'sortBy' => [
        [
            'key' => 'data.data.totali.value',
            'order' => 'desc'
        ]
    ]
];


$powerbi = [
    'resourceKey' => env('POWERBI_LAZIO_RESOURCEKEY'),
    'datasetId' => env('POWERBI_LAZIO_DATASETID'),
    'reportId' => env('POWERBI_LAZIO_REPORTID'),
    'visualId' => env('POWERBI_LAZIO_VISUALID'),
    'modelId' => env('POWERBI_LAZIO_MODELID'),
    'entity' => env('POWERBI_LAZIO_ENTITY'),
];

$url = env('POWERBI_LAZIO_URI_API');

$headers = [
    'Accept' => 'application/json, text/plain, */*',
    'Origin' => 'https://app.powerbi.com',
    'Referer' => 'https://app.powerbi.com/',
    'User-Agent' => 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/143.0.0.0 Safari/537.36',
];

return [
    'meta' => [
        'slug' => 'roma',
        'Titolo' => 'Roma'
    ],
    'websocket' => [
        'active' => true,
        'channel' => 'lazio.roma',
        'event' => 'data'
    ],
    'tableSettings' => $tableSettings,
    'ospedali' => [
        // Una sola query restituisce tutti i pronto soccorso del Lazio: il campo
        // 'codice' e' "STRUTTURA|COMUNE" come compare nel dataset e serve ad
        // abbinare la riga (il solo nome non basta, "Ospedale Civile" si ripete).
        'saluteLazioRoma' => [
            'cache' => [
                'key' => 'lazio.roma',
                'ttlMinute' => 1
            ],
            'url' => $url,
            'headers' => $headers,
            'powerbi' => $powerbi,
            'jobClass' => \App\Jobs\Lazio\SaluteLazioPowerBiJob::class,
            'data' => [
                'ospedali_riuniti' => [
                    'id' => 1,
                    'codice' => 'Ospedali Riuniti|Anzio',
                    'nome' => 'Anzio - Ospedali Riuniti',
                    'descrizione' => 'DEA di I livello, ASL RM6.',
                    'adulti' => true,
                    'indirizzo' => 'Via Cupa dei Marmi, 00048 Anzio RM',
                    'telefono' => '',
                    'email' => '',
                    'web' => 'https://www.salutelazio.it/',
                    'google_maps' => 'https://www.google.com/maps/search/?api=1&query=41.4605404,12.6367566',
                    'coords' => [
                        'lat' => '41.4605404',
                        'lng' => '12.6367566',
                    ],
                    'data' => [],
                ],
                'ospedale_dei_castelli' => [
                    'id' => 2,
                    'codice' => 'Ospedale dei Castelli|Ariccia',
                    'nome' => 'Ariccia - Ospedale dei Castelli',
                    'descrizione' => 'DEA di I livello, ASL RM6.',
                    'adulti' => true,
                    'indirizzo' => 'Via Nettunense, 00072 Ariccia RM',
                    'telefono' => '',
                    'email' => '',
                    'web' => 'https://www.salutelazio.it/',
                    'google_maps' => 'https://www.google.com/maps/search/?api=1&query=41.6771329,12.6482579',
                    'coords' => [
                        'lat' => '41.6771329',
                        'lng' => '12.6482579',
                    ],
                    'data' => [],
                ],
                'padre_pio' => [
                    'id' => 3,
                    'codice' => 'Padre Pio|Bracciano',
                    'nome' => 'Bracciano - Ospedale Padre Pio',
                    'descrizione' => 'Pronto soccorso, ASL RM4.',
                    'adulti' => true,
                    'indirizzo' => 'Via Santa Lucia, 00062 Bracciano RM',
                    'telefono' => '',
                    'email' => '',
                    'web' => 'https://www.salutelazio.it/',
                    'google_maps' => 'https://www.google.com/maps/search/?api=1&query=42.0962534,12.1731973',
                    'coords' => [
                        'lat' => '42.0962534',
                        'lng' => '12.1731973',
                    ],
                    'data' => [],
                ],
                'san_paolo' => [
                    'id' => 4,
                    'codice' => 'San Paolo|Civitavecchia',
                    'nome' => 'Civitavecchia - Ospedale San Paolo',
                    'descrizione' => 'DEA di I livello, ASL RM4.',
                    'adulti' => true,
                    'indirizzo' => 'Largo Donatori del Sangue 1, 00053 Civitavecchia RM',
                    'telefono' => '',
                    'email' => '',
                    'web' => 'https://www.salutelazio.it/',
                    'google_maps' => 'https://www.google.com/maps/search/?api=1&query=42.0981586,11.8097588',
                    'coords' => [
                        'lat' => '42.0981586',
                        'lng' => '11.8097588',
                    ],
                    'data' => [],
                ],
                'l_parodi_delfino' => [
                    'id' => 5,
                    'codice' => 'L. Parodi Delfino|Colleferro',
                    'nome' => 'Colleferro - Ospedale Leopoldo Parodi Delfino',
                    'descrizione' => 'Pronto soccorso, ASL RM5.',
                    'adulti' => true,
                    'indirizzo' => 'Piazza Aldo Moro 1, 00034 Colleferro RM',
                    'telefono' => '',
                    'email' => '',
                    'web' => 'https://www.salutelazio.it/',
                    'google_maps' => 'https://www.google.com/maps/search/?api=1&query=41.7276648,13.0045714',
                    'coords' => [
                        'lat' => '41.7276648',
                        'lng' => '13.0045714',
                    ],
                    'data' => [],
                ],
                'san_sebastiano_martire' => [
                    'id' => 6,
                    'codice' => 'San Sebastiano Martire|Frascati',
                    'nome' => 'Frascati - Ospedale San Sebastiano Martire',
                    'descrizione' => 'Pronto soccorso, ASL RM6.',
                    'adulti' => true,
                    'indirizzo' => 'Via Tuscolana 2, 00044 Frascati RM',
                    'telefono' => '',
                    'email' => '',
                    'web' => 'https://www.salutelazio.it/',
                    'google_maps' => 'https://www.google.com/maps/search/?api=1&query=41.8091805,12.6753309',
                    'coords' => [
                        'lat' => '41.8091805',
                        'lng' => '12.6753309',
                    ],
                    'data' => [],
                ],
                'santissimo_gonfalone' => [
                    'id' => 7,
                    'codice' => 'Santissimo Gonfalone|Monterotondo',
                    'nome' => 'Monterotondo - Ospedale Santissimo Gonfalone',
                    'descrizione' => 'Pronto soccorso, ASL RM5.',
                    'adulti' => true,
                    'indirizzo' => 'Via Salaria, 00015 Monterotondo RM',
                    'telefono' => '',
                    'email' => '',
                    'web' => 'https://www.salutelazio.it/',
                    'google_maps' => 'https://www.google.com/maps/search/?api=1&query=42.0656472,12.5935490',
                    'coords' => [
                        'lat' => '42.0656472',
                        'lng' => '12.5935490',
                    ],
                    'data' => [],
                ],
                'coniugi_bernardini' => [
                    'id' => 8,
                    'codice' => 'Coniugi Bernardini|Palestrina',
                    'nome' => 'Palestrina - Ospedale Coniugi Bernardini',
                    'descrizione' => 'Pronto soccorso, ASL RM5.',
                    'adulti' => true,
                    'indirizzo' => 'Viale Pio XII 42, 00036 Palestrina RM',
                    'telefono' => '',
                    'email' => '',
                    'web' => 'https://www.salutelazio.it/',
                    'google_maps' => 'https://www.google.com/maps/search/?api=1&query=41.8364541,12.8863273',
                    'coords' => [
                        'lat' => '41.8364541',
                        'lng' => '12.8863273',
                    ],
                    'data' => [],
                ],
                'bambino_gesu_palidoro' => [
                    'id' => 9,
                    'codice' => 'Bambino Gesu\' Palidoro|Palidoro',
                    'nome' => 'Palidoro - Ospedale Pediatrico Bambino Gesù - sede di Palidoro',
                    'descrizione' => 'DEA di I livello, ASL RM3.',
                    'adulti' => false,
                    'indirizzo' => 'Via della Torre di Palidoro, 00050 Fiumicino RM',
                    'telefono' => '',
                    'email' => '',
                    'web' => 'https://www.salutelazio.it/',
                    'google_maps' => 'https://www.google.com/maps/search/?api=1&query=41.9192319,12.1417199',
                    'coords' => [
                        'lat' => '41.9192319',
                        'lng' => '12.1417199',
                    ],
                    'data' => [],
                ],
                'sant_anna' => [
                    'id' => 10,
                    'codice' => 'Sant\'Anna|Pomezia',
                    'nome' => 'Pomezia - Casa di Cura Sant\'Anna',
                    'descrizione' => 'Pronto soccorso, ASL RM6.',
                    'adulti' => true,
                    'indirizzo' => 'Via del Mare 69/71, 00071 Pomezia RM',
                    'telefono' => '',
                    'email' => '',
                    'web' => 'https://www.salutelazio.it/',
                    'google_maps' => 'https://www.google.com/maps/search/?api=1&query=41.6720582,12.4963055',
                    'coords' => [
                        'lat' => '41.6720582',
                        'lng' => '12.4963055',
                    ],
                    'data' => [],
                ],
                'aurelia_hospital' => [
                    'id' => 11,
                    'codice' => 'Aurelia Hospital|Roma',
                    'nome' => 'Roma - Aurelia Hospital',
                    'descrizione' => 'DEA di I livello, ASL RM1.',
                    'adulti' => true,
                    'indirizzo' => 'Via Bogliasco, 00163 Roma RM',
                    'telefono' => '',
                    'email' => '',
                    'web' => 'https://www.salutelazio.it/',
                    'google_maps' => 'https://www.google.com/maps/search/?api=1&query=41.8870757,12.3983943',
                    'coords' => [
                        'lat' => '41.8870757',
                        'lng' => '12.3983943',
                    ],
                    'data' => [],
                ],
                'bambino_gesu' => [
                    'id' => 12,
                    'codice' => 'Bambino Gesu\'|Roma',
                    'nome' => 'Roma - Ospedale Pediatrico Bambino Gesù',
                    'descrizione' => 'DEA di II livello, ASL RM1.',
                    'adulti' => false,
                    'indirizzo' => 'Piazza di Sant\'Onofrio 4, 00165 Roma RM',
                    'telefono' => '',
                    'email' => '',
                    'web' => 'https://www.salutelazio.it/',
                    'google_maps' => 'https://www.google.com/maps/search/?api=1&query=41.8970772,12.4607003',
                    'coords' => [
                        'lat' => '41.8970772',
                        'lng' => '12.4607003',
                    ],
                    'data' => [],
                ],
                'c_t_o_andrea_alesini' => [
                    'id' => 13,
                    'codice' => 'C.T.O. Andrea Alesini|Roma',
                    'nome' => 'Roma - C.T.O. Andrea Alesini',
                    'descrizione' => 'Pronto soccorso specialistico, ASL RM2.',
                    'adulti' => true,
                    'indirizzo' => 'Via San Nemesio 21, 00145 Roma RM',
                    'telefono' => '',
                    'email' => '',
                    'web' => 'https://www.salutelazio.it/',
                    'google_maps' => 'https://www.google.com/maps/search/?api=1&query=41.8594935,12.4867280',
                    'coords' => [
                        'lat' => '41.8594935',
                        'lng' => '12.4867280',
                    ],
                    'data' => [],
                ],
                'campus_biomedico' => [
                    'id' => 14,
                    'codice' => 'Campus Biomedico|Roma',
                    'nome' => 'Roma - Policlinico Universitario Campus Bio-Medico',
                    'descrizione' => 'DEA di I livello, ASL RM2.',
                    'adulti' => true,
                    'indirizzo' => 'Via Alvaro del Portillo, 00128 Roma RM',
                    'telefono' => '',
                    'email' => '',
                    'web' => 'https://www.salutelazio.it/',
                    'google_maps' => 'https://www.google.com/maps/search/?api=1&query=41.7703628,12.4696035',
                    'coords' => [
                        'lat' => '41.7703628',
                        'lng' => '12.4696035',
                    ],
                    'data' => [],
                ],
                'cristo_re' => [
                    'id' => 15,
                    'codice' => 'Cristo Re|Roma',
                    'nome' => 'Roma - Ospedale Cristo Re',
                    'descrizione' => 'Pronto soccorso, ASL RM1.',
                    'adulti' => true,
                    'indirizzo' => 'Via Cardinale Garampi, 00167 Roma RM',
                    'telefono' => '',
                    'email' => '',
                    'web' => 'https://www.salutelazio.it/',
                    'google_maps' => 'https://www.google.com/maps/search/?api=1&query=41.9181322,12.4210287',
                    'coords' => [
                        'lat' => '41.9181322',
                        'lng' => '12.4210287',
                    ],
                    'data' => [],
                ],
                'fbf_gemelli_isola_tiberina' => [
                    'id' => 16,
                    'codice' => 'FBF-Gemelli Isola Tiberina|Roma',
                    'nome' => 'Roma - Fatebenefratelli Isola Tiberina',
                    'descrizione' => 'DEA di I livello, ASL RM1.',
                    'adulti' => true,
                    'indirizzo' => 'Via di Ponte Quattro Capi 39, 00186 Roma RM',
                    'telefono' => '',
                    'email' => '',
                    'web' => 'https://www.salutelazio.it/',
                    'google_maps' => 'https://www.google.com/maps/search/?api=1&query=41.8909123,12.4769258',
                    'coords' => [
                        'lat' => '41.8909123',
                        'lng' => '12.4769258',
                    ],
                    'data' => [],
                ],
                'g_battista_grassi' => [
                    'id' => 17,
                    'codice' => 'G. Battista Grassi|Roma',
                    'nome' => 'Roma - Ospedale Giovanni Battista Grassi',
                    'descrizione' => 'DEA di I livello, ASL RM3.',
                    'adulti' => true,
                    'indirizzo' => 'Via Giancarlo Passeroni 28, 00122 Roma RM',
                    'telefono' => '',
                    'email' => '',
                    'web' => 'https://www.salutelazio.it/',
                    'google_maps' => 'https://www.google.com/maps/search/?api=1&query=41.7282811,12.3000352',
                    'coords' => [
                        'lat' => '41.7282811',
                        'lng' => '12.3000352',
                    ],
                    'data' => [],
                ],
                'madre_g_vannini' => [
                    'id' => 18,
                    'codice' => 'Madre G. Vannini|Roma',
                    'nome' => 'Roma - Ospedale Madre G. Vannini',
                    'descrizione' => 'DEA di I livello, ASL RM2.',
                    'adulti' => true,
                    'indirizzo' => 'Via di Acqua Bullicante 4, 00177 Roma RM',
                    'telefono' => '',
                    'email' => '',
                    'web' => 'https://www.salutelazio.it/',
                    'google_maps' => 'https://www.google.com/maps/search/?api=1&query=41.8809797,12.5434057',
                    'coords' => [
                        'lat' => '41.8809797',
                        'lng' => '12.5434057',
                    ],
                    'data' => [],
                ],
                'oftalmico' => [
                    'id' => 19,
                    'codice' => 'Oftalmico|Roma',
                    'nome' => 'Roma - Ospedale Oftalmico',
                    'descrizione' => 'Pronto soccorso specialistico, ASL RM1.',
                    'adulti' => true,
                    'indirizzo' => 'Via Cipro 3, 00136 Roma RM',
                    'telefono' => '',
                    'email' => '',
                    'web' => 'https://www.salutelazio.it/',
                    'google_maps' => 'https://www.google.com/maps/search/?api=1&query=41.9081182,12.4484657',
                    'coords' => [
                        'lat' => '41.9081182',
                        'lng' => '12.4484657',
                    ],
                    'data' => [],
                ],
                'pol_univ_a_gemelli' => [
                    'id' => 20,
                    'codice' => 'Pol. Univ. A. Gemelli|Roma',
                    'nome' => 'Roma - Policlinico Universitario Agostino Gemelli',
                    'descrizione' => 'DEA di II livello, ASL RM1.',
                    'adulti' => true,
                    'indirizzo' => 'Largo Agostino Gemelli 8, 00168 Roma RM',
                    'telefono' => '',
                    'email' => '',
                    'web' => 'https://www.salutelazio.it/',
                    'google_maps' => 'https://www.google.com/maps/search/?api=1&query=41.9315345,12.4294393',
                    'coords' => [
                        'lat' => '41.9315345',
                        'lng' => '12.4294393',
                    ],
                    'data' => [],
                ],
                'pol_univ_tor_vergata' => [
                    'id' => 21,
                    'codice' => 'Pol. Univ. Tor Vergata|Roma',
                    'nome' => 'Roma - Policlinico Tor Vergata',
                    'descrizione' => 'DEA di II livello, ASL RM2.',
                    'adulti' => true,
                    'indirizzo' => 'Viale Oxford 81, 00133 Roma RM',
                    'telefono' => '',
                    'email' => '',
                    'web' => 'https://www.salutelazio.it/',
                    'google_maps' => 'https://www.google.com/maps/search/?api=1&query=41.8576274,12.6309806',
                    'coords' => [
                        'lat' => '41.8576274',
                        'lng' => '12.6309806',
                    ],
                    'data' => [],
                ],
                'pol_univ_umberto_i' => [
                    'id' => 22,
                    'codice' => 'Pol. Univ. Umberto I|Roma',
                    'nome' => 'Roma - Policlinico Umberto I',
                    'descrizione' => 'DEA di II livello, ASL RM1.',
                    'adulti' => true,
                    'indirizzo' => 'Viale del Policlinico 155, 00161 Roma RM',
                    'telefono' => '',
                    'email' => '',
                    'web' => 'https://www.salutelazio.it/',
                    'google_maps' => 'https://www.google.com/maps/search/?api=1&query=41.9064570,12.5121255',
                    'coords' => [
                        'lat' => '41.9064570',
                        'lng' => '12.5121255',
                    ],
                    'data' => [],
                ],
                'policlinico_casilino' => [
                    'id' => 23,
                    'codice' => 'Policlinico Casilino|Roma',
                    'nome' => 'Roma - Policlinico Casilino',
                    'descrizione' => 'DEA di I livello, ASL RM2.',
                    'adulti' => true,
                    'indirizzo' => 'Via Casilina 1049, 00169 Roma RM',
                    'telefono' => '',
                    'email' => '',
                    'web' => 'https://www.salutelazio.it/',
                    'google_maps' => 'https://www.google.com/maps/search/?api=1&query=41.8686656,12.5895908',
                    'coords' => [
                        'lat' => '41.8686656',
                        'lng' => '12.5895908',
                    ],
                    'data' => [],
                ],
                'san_camillo_forlanini' => [
                    'id' => 24,
                    'codice' => 'San Camillo-Forlanini|Roma',
                    'nome' => 'Roma - Ospedale San Camillo-Forlanini',
                    'descrizione' => 'DEA di II livello, ASL RM3.',
                    'adulti' => true,
                    'indirizzo' => 'Circonvallazione Gianicolense 87, 00152 Roma RM',
                    'telefono' => '',
                    'email' => '',
                    'web' => 'https://www.salutelazio.it/',
                    'google_maps' => 'https://www.google.com/maps/search/?api=1&query=41.8695994,12.4559991',
                    'coords' => [
                        'lat' => '41.8695994',
                        'lng' => '12.4559991',
                    ],
                    'data' => [],
                ],
                'san_carlo_di_nancy' => [
                    'id' => 25,
                    'codice' => 'San Carlo di Nancy|Roma',
                    'nome' => 'Roma - Ospedale San Carlo di Nancy',
                    'descrizione' => 'Pronto soccorso, ASL RM1.',
                    'adulti' => true,
                    'indirizzo' => 'Via Aurelia, 00165 Roma RM',
                    'telefono' => '',
                    'email' => '',
                    'web' => 'https://www.salutelazio.it/',
                    'google_maps' => 'https://www.google.com/maps/search/?api=1&query=41.8975780,12.4386999',
                    'coords' => [
                        'lat' => '41.8975780',
                        'lng' => '12.4386999',
                    ],
                    'data' => [],
                ],
                'san_filippo_neri' => [
                    'id' => 26,
                    'codice' => 'San Filippo Neri|Roma',
                    'nome' => 'Roma - Ospedale San Filippo Neri',
                    'descrizione' => 'DEA di I livello, ASL RM1.',
                    'adulti' => true,
                    'indirizzo' => 'Via Giovanni Martinotti 20, 00135 Roma RM',
                    'telefono' => '',
                    'email' => '',
                    'web' => 'https://www.salutelazio.it/',
                    'google_maps' => 'https://www.google.com/maps/search/?api=1&query=41.9477432,12.4136326',
                    'coords' => [
                        'lat' => '41.9477432',
                        'lng' => '12.4136326',
                    ],
                    'data' => [],
                ],
                'san_giovanni_addolorata' => [
                    'id' => 27,
                    'codice' => 'San Giovanni Addolorata|Roma',
                    'nome' => 'Roma - Ospedale San Giovanni Addolorata',
                    'descrizione' => 'DEA di II livello, ASL RM1.',
                    'adulti' => true,
                    'indirizzo' => 'Via di Santo Stefano Rotondo 4, 00184 Roma RM',
                    'telefono' => '',
                    'email' => '',
                    'web' => 'https://www.salutelazio.it/',
                    'google_maps' => 'https://www.google.com/maps/search/?api=1&query=41.8852718,12.4986193',
                    'coords' => [
                        'lat' => '41.8852718',
                        'lng' => '12.4986193',
                    ],
                    'data' => [],
                ],
                'san_pietro_fbf' => [
                    'id' => 28,
                    'codice' => 'San Pietro-FBF|Roma',
                    'nome' => 'Roma - Ospedale San Pietro Fatebenefratelli',
                    'descrizione' => 'DEA di I livello, ASL RM1.',
                    'adulti' => true,
                    'indirizzo' => 'Via dei Due Ponti, 00189 Roma RM',
                    'telefono' => '',
                    'email' => '',
                    'web' => 'https://www.salutelazio.it/',
                    'google_maps' => 'https://www.google.com/maps/search/?api=1&query=41.9647376,12.4523915',
                    'coords' => [
                        'lat' => '41.9647376',
                        'lng' => '12.4523915',
                    ],
                    'data' => [],
                ],
                'sandro_pertini' => [
                    'id' => 29,
                    'codice' => 'Sandro Pertini|Roma',
                    'nome' => 'Roma - Ospedale Sandro Pertini',
                    'descrizione' => 'DEA di I livello, ASL RM2.',
                    'adulti' => true,
                    'indirizzo' => 'Via dei Monti Tiburtini 385, 00157 Roma RM',
                    'telefono' => '',
                    'email' => '',
                    'web' => 'https://www.salutelazio.it/',
                    'google_maps' => 'https://www.google.com/maps/search/?api=1&query=41.9205448,12.5403454',
                    'coords' => [
                        'lat' => '41.9205448',
                        'lng' => '12.5403454',
                    ],
                    'data' => [],
                ],
                'sant_andrea' => [
                    'id' => 30,
                    'codice' => 'Sant\'Andrea|Roma',
                    'nome' => 'Roma - Ospedale Sant\'Andrea',
                    'descrizione' => 'DEA di I livello, ASL RM1.',
                    'adulti' => true,
                    'indirizzo' => 'Via di Grottarossa 1035, 00189 Roma RM',
                    'telefono' => '',
                    'email' => '',
                    'web' => 'https://www.salutelazio.it/',
                    'google_maps' => 'https://www.google.com/maps/search/?api=1&query=41.9830777,12.4703776',
                    'coords' => [
                        'lat' => '41.9830777',
                        'lng' => '12.4703776',
                    ],
                    'data' => [],
                ],
                'sant_eugenio' => [
                    'id' => 31,
                    'codice' => 'Sant\'Eugenio|Roma',
                    'nome' => 'Roma - Ospedale Sant\'Eugenio',
                    'descrizione' => 'DEA di I livello, ASL RM2.',
                    'adulti' => true,
                    'indirizzo' => 'Piazzale dell\'Umanesimo 10, 00144 Roma RM',
                    'telefono' => '',
                    'email' => '',
                    'web' => 'https://www.salutelazio.it/',
                    'google_maps' => 'https://www.google.com/maps/search/?api=1&query=41.8212530,12.4722581',
                    'coords' => [
                        'lat' => '41.8212530',
                        'lng' => '12.4722581',
                    ],
                    'data' => [],
                ],
                'santo_spirito' => [
                    'id' => 32,
                    'codice' => 'Santo Spirito|Roma',
                    'nome' => 'Roma - Ospedale Santo Spirito',
                    'descrizione' => 'DEA di I livello, ASL RM1.',
                    'adulti' => true,
                    'indirizzo' => 'Pista ciclabile del Tevere, 00120 Roma RM',
                    'telefono' => '',
                    'email' => '',
                    'web' => 'https://www.salutelazio.it/',
                    'google_maps' => 'https://www.google.com/maps/search/?api=1&query=41.9010559,12.4625575',
                    'coords' => [
                        'lat' => '41.9010559',
                        'lng' => '12.4625575',
                    ],
                    'data' => [],
                ],
                'a_angelucci' => [
                    'id' => 33,
                    'codice' => 'A. Angelucci|Subiaco',
                    'nome' => 'Subiaco - Ospedale Arnaldo Angelucci',
                    'descrizione' => 'Pronto soccorso, ASL RM5.',
                    'adulti' => true,
                    'indirizzo' => 'SP40b, 00028 Subiaco RM',
                    'telefono' => '',
                    'email' => '',
                    'web' => 'https://www.salutelazio.it/',
                    'google_maps' => 'https://www.google.com/maps/search/?api=1&query=41.9322074,13.0862927',
                    'coords' => [
                        'lat' => '41.9322074',
                        'lng' => '13.0862927',
                    ],
                    'data' => [],
                ],
                'san_giovanni_evangelista' => [
                    'id' => 34,
                    'codice' => 'San Giovanni Evangelista|Tivoli',
                    'nome' => 'Tivoli - Ospedale San Giovanni Evangelista',
                    'descrizione' => 'DEA di I livello, ASL RM5.',
                    'adulti' => true,
                    'indirizzo' => 'Via Antonio Parrozzani 3, 00019 Tivoli RM',
                    'telefono' => '',
                    'email' => '',
                    'web' => 'https://www.salutelazio.it/',
                    'google_maps' => 'https://www.google.com/maps/search/?api=1&query=41.9605572,12.8024289',
                    'coords' => [
                        'lat' => '41.9605572',
                        'lng' => '12.8024289',
                    ],
                    'data' => [],
                ],
                'p_colombo' => [
                    'id' => 35,
                    'codice' => 'P. Colombo|Velletri',
                    'nome' => 'Velletri - Ospedale Paolo Colombo',
                    'descrizione' => 'DEA di I livello, ASL RM6.',
                    'adulti' => true,
                    'indirizzo' => 'Via Orti Ginnetti, 00049 Velletri RM',
                    'telefono' => '',
                    'email' => '',
                    'web' => 'https://www.salutelazio.it/',
                    'google_maps' => 'https://www.google.com/maps/search/?api=1&query=41.6866430,12.7810938',
                    'coords' => [
                        'lat' => '41.6866430',
                        'lng' => '12.7810938',
                    ],
                    'data' => [],
                ],
            ]
        ],
    ]
];
